INSERT INTO listings (user_id, title, description, price, category, stock, is_featured, image_url, is_deleted)
VALUES
  (8, 'Laptop for Sale', 'Used laptop in good condition', 500, 'Electronics', 3, true, 'https://m.media-amazon.com/images/I/71p-M3sPhhL.jpg', false),
  (8, 'Designer Dress', 'Brand new designer dress for special occasions', 150, 'Clothing', 5, false, 'https://cdn.fs.grailed.com/api/file/secjGcqzSumyP8Ctq6m3', false),
  (8, 'Antique Table', 'Beautiful antique wooden table', 300, 'Furniture', 1, true, 'https://www.thebrick.com/cdn/shop/products/che3rdtl_hc_1400x.jpg?v=1627659075', false),
  (8, 'Gaming Console', 'Latest gaming console with controllers', 400, 'Electronics', 2, false, 'https://m.media-amazon.com/images/I/71NBQ2a52CL.jpg', false),
  (8, 'Leather Sofa', 'Luxurious leather sofa for your living room', 800, 'Furniture', 1, false, 'https://www.thebrick.com/cdn/shop/products/lotugysf_hc_1400x.jpg?v=1683220713', false),
  (8, 'Smartphone', 'Brand new smartphone with advanced features', 350, 'Electronics', 3, false, 'https://akm-img-a-in.tosshub.com/indiatoday/images/story/202307/iphone_15_launch_0-sixteen_nine.png?VersionId=MRvBAv6y.tPXaCO91Hf8U61bxp37BJmY&size=690:388', false),
  (8, 'Desk Chair', 'Comfortable desk chair for long hours of work', 100, 'Furniture', 4, false, 'https://m.media-amazon.com/images/I/716tq9Y8WOL.jpg', false),
  (6, 'Headphones', 'High-quality headphones for music enthusiasts', 70, 'Electronics', 6, true, 'https://www.beatsbydre.com/content/dam/beats/web/product/headphones/studiopro-wireless/pdp/product-carousel/black/pc-studiopro-black-thrqtr-right.jpg', false),
  (6, 'Camera', 'Professional-grade camera for photography', 600, 'Electronics', 1, false, 'https://m.media-amazon.com/images/I/61BKYlNqH6L._AC_UF894,1000_QL80_.jpg', false),
  (6, 'Laptop Bag', 'Stylish laptop bag for professionals', 30, 'Clothing', 7, true, 'https://m.media-amazon.com/images/I/91sLOZjNWHL._AC_UF894,1000_QL80_.jpg', false),
  (6, 'Digital Watch', 'Digital watch with multiple functions', 50, 'Clothing', 5, false, 'https://m.media-amazon.com/images/I/71-+WIi-X3L._AC_SL1500_.jpg', false),
  (6, 'Desktop Computer', 'High-performance desktop computer', 800, 'Electronics', 1, true, 'https://cdn.shopify.com/s/files/1/1918/7539/files/61-MgG9cBwL._AC_SX679_480x480.jpg?v=1647832243', false),
  (4, 'Coffee Table', 'Stylish coffee table for your living room', 80, 'Furniture', 5, true, 'https://www.scandesigns.com/wp-content/uploads/2020/01/beta-coffee-table-black-2-scaled.jpg', false),
  (4, 'Digital Camera', 'Compact digital camera for photography', 200, 'Electronics', 2, false, 'https://m.media-amazon.com/images/I/71JDnICC3nL.jpg', false),
  (4, 'Office Chair', 'Ergonomic office chair for comfort', 150, 'Furniture', 3, false, 'https://m.media-amazon.com/images/I/71ohGSWApfL._AC_UF1000,1000_QL80_.jpg', false),
  (4, 'Desk Lamp', 'Modern desk lamp for workspace illumination', 35, 'Electronics', 6, true, 'https://cb2.scene7.com/is/image/CB2/KMPolarTableLampSHS21/$web_pdp_main_carousel_sm$/210210135642/polar-table-lamp.jpg', false),
  (4, 'Desktop Monitor', 'Large desktop monitor for multitasking', 150, 'Electronics', 3, true, 'https://m.media-amazon.com/images/I/51v6h2TfPCL.jpg', false),
  (4, 'Microwave Oven', 'Compact microwave oven for quick heating', 40, 'Electronics', 5, true, 'https://upload.wikimedia.org/wikipedia/commons/0/08/Panasonic_NN-SD69LS_20220410.jpg', false),
  (4, 'Digital Piano', 'Digital piano with weighted keys', 300, 'Electronics', 1, false, 'https://m.media-amazon.com/images/I/61YcyKT0ahL._AC_UF1000,1000_QL80_.jpg', false),
  (2, 'Tablet', 'Tablet with a high-resolution display', 300, 'Electronics', 2, true, 'https://p3-ofp.static.pub/ShareResource/na/products/yoga/560x450/lenovo-yoga-tab-11-07.png', false),
  (2, 'Wristwatch', 'Elegant wristwatch for both formal and casual wear', 120, 'Clothing', 5, false, 'https://www.skagen.com/on/demandware.static/-/Library-Sites-SkagenSharedLibrary/default/dw534b3957/2023/FA23/set_08282023_global/Slices/HP_08282023/8.28Kuppel_HP_M1.jpg', false),
  (2, 'Coffee Maker', 'Automatic coffee maker for coffee lovers', 50, 'Electronics', 5, false, 'https://media-www.canadiantire.ca/product/living/kitchen/kitchen-appliances/0430986/delonghi-true-brew-single-serve-drip-coffee-maker-98a33180-70ad-4a00-9e49-11981cf9e0f0-jpgrendition.jpg', false),
  (2, 'Smart Speaker', 'Voice-controlled smart speaker', 75, 'Electronics', 4, false, 'https://images.homedepot.ca/productimages/p_1001066007.jpg?product-images=l', false),
  (2, 'Digital Scale', 'Digital kitchen scale for precise measurements', 25, 'Electronics', 5, false, 'https://m.media-amazon.com/images/I/61+oYg+i82L._AC_UF1000,1000_QL80_.jpg', false),
  (2, 'Kitchen Blender', 'Powerful blender for making smoothies', 40, 'Electronics', 3, false, 'https://m.media-amazon.com/images/I/61OVQA0Bu3L.jpg', false),
  (2, 'Toaster', 'Compact toaster for quick breakfasts', 20, 'Electronics', 8, true, 'https://m.media-amazon.com/images/I/71n-oeNV6BL.jpg', false),
  (2, 'Digital Scale', 'Digital kitchen scale for precise measurements', 25, 'Electronics', 5, false, 'https://canada.newark.com/productimages/large/en_GB/IN08761-40.jpg', false),
  (45, 'Coffee Maker', 'Automatic coffee maker for coffee lovers', 50, 'Electronics', 5, false, 'https://m.media-amazon.com/images/I/61tGBNWRI3L.jpg', false),
  (45, 'Smart Speaker', 'Voice-controlled smart speaker', 75, 'Electronics', 4, false, 'https://m.media-amazon.com/images/I/61TSAn9KKxL._AC_UF894,1000_QL80_.jpg', false),
  (45, 'Digital Scale', 'Digital kitchen scale for precise measurements', 25, 'Electronics', 5, false, 'https://media-www.canadiantire.ca/product/living/kitchen/kitchen-tools-thermometers/1424303/accuweight-compact-digital-kitchen-scale-3kg-capacity-72f60cd6-d6de-4574-99b6-ec854695c8f9.png', false),
  (45, 'Kitchen Blender', 'Powerful blender for making smoothies', 40, 'Electronics', 3, false, 'https://i5.walmartimages.ca/images/Large/151/192/6000205151192.jpg', false),
  (45, 'Toaster', 'Compact toaster for quick breakfasts', 20, 'Electronics', 8, true, 'https://www.koolatron.ca/cdn/shop/products/KKTS2SS-ECOM-01.jpg?v=1657746941', false)
  ;